"""Idempotent 15-quiz Generative AI curriculum seed."""
from app.extensions import db
from app.models.course import Course
from app.models.quiz import Quiz, QuizQuestion
from app.models.user import User


def _fact(concept, answer, distractors, scenario, scenario_answer, scenario_distractors):
    return {
        'concept': concept,
        'answer': answer,
        'distractors': distractors,
        'scenario': scenario,
        'scenario_answer': scenario_answer,
        'scenario_distractors': scenario_distractors,
    }


def _questions(facts):
    questions = []
    for fact in facts:
        variants = [
            (f"Which statement best describes {fact['concept']}?",
             fact['answer'], fact['distractors']),
            (fact['scenario'], fact['scenario_answer'], fact['scenario_distractors']),
            (f"Which practice is most appropriate when working with {fact['concept']}?",
             fact['answer'], fact['distractors']),
        ]
        for text, answer, distractors in variants:
            options = [answer] + list(distractors)
            rotation = len(questions) % 4
            options = options[rotation:] + options[:rotation]
            questions.append({
                'question_text': text,
                'options': options,
                'correct_option': 'ABCD'[options.index(answer)],
                'explanation': f"{answer} is correct because it is the defining practical idea for {fact['concept']}.",
                'order_index': len(questions),
            })
    return questions


TOPICS = [
    ('Generative AI Fundamentals', [
        _fact('generative AI', 'systems that create new content from learned patterns', ['systems that only sort existing records', 'rules that never produce output', 'a database backup process'], 'A team wants a model to draft product descriptions from a short brief. What capability is needed?', 'content generation from learned patterns', ['only database indexing', 'a spreadsheet formula', 'a fixed file copy']),
        _fact('training data', 'examples used to learn statistical patterns', ['only the final user prompt', 'a hardware configuration file', 'a password list'], 'A model performs better after seeing many labeled examples. What changed?', 'the model received useful training examples', ['the context window was removed', 'the model stopped using parameters', 'the tokenizer was deleted']),
        _fact('generative output', 'a new response sampled from the model distribution', ['a guaranteed lookup from one database row', 'a compiler error by definition', 'an unchanged copy of the prompt'], 'Two runs give different but relevant phrasings. What is this variation?', 'sampling variation in generated output', ['database corruption', 'a missing model', 'proof that one answer is always false']),
        _fact('AI limitations', 'a fluent response can still be inaccurate', ['fluent text is always verified', 'models cannot produce text', 'all model errors are syntax errors'], 'A polished answer includes a nonexistent citation. What should the user do?', 'verify the claim against a trusted source', ['publish it without review', 'assume citations are always real', 'remove all context']),
        _fact('use-case fit', 'match the model capability to the task and risk', ['use the largest model for every task', 'avoid evaluation for every task', 'let the model decide its own permissions'], 'A chatbot gives medical guidance. What extra consideration matters most?', 'careful review, safety limits, and qualified oversight', ['longer greetings', 'random temperature increases', 'removing refusal rules']),
        _fact('model output', 'an output should be treated as a suggestion until checked', ['an output is automatically a legal decision', 'an output cannot contain uncertainty', 'an output is always private'], 'A generated summary will be sent to customers. What is a sensible step?', 'review it for accuracy and sensitive information', ['skip review because it is concise', 'hide the prompt from reviewers', 'increase randomness only']),
        _fact('generative versus retrieval', 'generation creates text while retrieval finds supporting information', ['generation and retrieval are identical', 'retrieval always writes new paragraphs', 'generation can only return database IDs'], 'A system must quote an approved policy. Which component helps locate the policy?', 'retrieval of the approved source', ['random sampling', 'a larger font', 'a blank prompt']),
        _fact('AI-assisted work', 'humans should remain accountable for consequential decisions', ['the model becomes legally responsible', 'review is unnecessary', 'confidence wording guarantees truth'], 'A model ranks job applicants. What is responsible deployment?', 'audit the process and keep human decision oversight', ['accept every ranking blindly', 'hide the model from applicants', 'remove evaluation data']),
        _fact('modalities', 'different data types can be processed by multimodal systems', ['only integers can be processed', 'modalities are database tables', 'text and images are always identical'], 'A model describes an uploaded chart and answers a text question. What is involved?', 'multimodal processing', ['only token deletion', 'file compression alone', 'a password reset']),
        _fact('generative model evaluation', 'evaluate outputs against task-specific quality criteria', ['judge quality only by response length', 'use one random example forever', 'avoid comparing outputs'], 'A marketing generator is tested. Which measure is useful?', 'accuracy, relevance, tone, and safety against a rubric', ['number of hidden layers only', 'screen brightness', 'prompt character count only']),
    ]),
    ('AI, Machine Learning, and Generative AI', [
        _fact('artificial intelligence', 'the broad field of systems performing tasks associated with human intelligence', ['only image generation', 'only neural networks', 'only database storage'], 'A rule-based route planner is categorized at what broad level?', 'artificial intelligence', ['only generative AI', 'only tokenization', 'not computing']),
        _fact('machine learning', 'systems that learn patterns from data instead of only explicit rules', ['systems that never use data', 'a method for formatting prompts', 'a type of monitor'], 'A model learns to classify spam from examples. What approach is this?', 'machine learning', ['manual HTML styling', 'file compression', 'random guessing']),
        _fact('supervised learning', 'learning from examples with target labels', ['learning without any examples', 'generating images from noise only', 'deleting labels'], 'A dataset marks emails as spam or safe. What kind of learning uses those labels?', 'supervised learning', ['unsupervised learning only', 'prompt chaining', 'token merging']),
        _fact('unsupervised learning', 'finding structure in data without target labels', ['requiring a correct label for every row', 'always generating text', 'executing a system prompt'], 'A system groups customers without predefined group names. What is likely used?', 'unsupervised learning', ['supervised classification only', 'manual grading', 'function calling']),
        _fact('generative machine learning', 'learning a distribution that can produce new examples', ['only counting rows', 'only selecting a known record', 'never producing content'], 'A model creates a new image resembling its training style. What distinguishes it?', 'it generates a new example from learned patterns', ['it only sorts images', 'it returns a stored filename', 'it disables inference']),
        _fact('classification', 'predicting a category or label', ['creating arbitrary paragraphs', 'retrieving every document', 'changing a database schema'], 'A support model labels tickets as billing or technical. What task is this?', 'classification', ['free-form generation', 'image upscaling', 'prompt tokenization']),
        _fact('regression', 'predicting a numeric value', ['predicting only a text label', 'choosing a prompt role', 'retrieving a paragraph'], 'A model estimates delivery time in minutes. What kind of prediction is it?', 'regression', ['classification', 'tokenization', 'few-shot prompting']),
        _fact('deep learning', 'machine learning using multi-layer neural networks', ['a rule with no learned parameters', 'a database query language', 'a prompt formatting style'], 'A vision model learns layered visual features. Which approach is likely?', 'deep learning', ['manual sorting', 'plain text search', 'CSV validation']),
        _fact('narrow AI', 'a system designed for a limited task', ['a system that performs every human task', 'a synonym for a database', 'a model with no objective'], 'A model detects defects on one product line. How should it be described?', 'narrow AI for a specific task', ['general human intelligence', 'a universal agent', 'a text editor']),
        _fact('AI pipeline choice', 'choose the simplest suitable method for the requirement', ['always select generative AI', 'avoid measuring the task', 'use training data without permission'], 'A fixed tax calculation must be exact. What is often preferable?', 'deterministic rules or validated software', ['uncontrolled generation', 'high temperature sampling', 'an ungrounded chatbot']),
    ]),
    ('Generative Models', [
        _fact('probability distribution', 'a model assigns likelihoods to possible outputs', ['a list of guaranteed facts', 'a hardware temperature reading', 'a CSS stylesheet'], 'Why can a model choose different valid next tokens?', 'several continuations can have different probabilities', ['the prompt is ignored', 'the model has no vocabulary', 'the output is retrieved exactly']),
        _fact('autoregressive generation', 'predicting the next token using previous context', ['writing the entire answer without sequential prediction', 'retrieving a fixed file only', 'training without examples'], 'A language model writes one token after another. What process is this?', 'autoregressive generation', ['batch deletion', 'image indexing', 'manual labeling']),
        _fact('diffusion model', 'iteratively denoising toward a generated sample', ['sorting pixels alphabetically', 'retrieving a web page', 'copying one image byte-for-byte'], 'An image model starts from noise and gradually forms a picture. What family fits?', 'diffusion model', ['a SQL join', 'a tokenizer only', 'a rule engine']),
        _fact('latent representation', 'a compact learned representation of important features', ['a user password', 'a final answer guarantee', 'a network cable'], 'Why might a model use a latent space?', 'to represent useful patterns compactly', ['to remove all information', 'to prevent inference', 'to store only labels']),
        _fact('sampling', 'selecting an output from probabilities', ['always returning the highest word alphabetically', 'deleting low probability tokens from training', 'turning text into HTML'], 'What does sampling control during generation?', 'which candidate continuation is selected', ['the database schema', 'the user identity', 'the model license']),
        _fact('conditional generation', 'generating based on provided input or condition', ['generating without any signal', 'only sorting input rows', 'removing the prompt'], 'An image model creates a dog image from a text description. What is the text?', 'a generation condition', ['a database key', 'an evaluation label only', 'a hidden password']),
        _fact('model parameters', 'learned values adjusted during training', ['only user interface colors', 'the prompt history alone', 'a list of URLs'], 'What do training updates change in a neural model?', 'learned parameter values', ['the browser buttons', 'the user role', 'the file extension']),
        _fact('generation-time inference', 'using a trained model to produce an output', ['changing training data labels', 'designing a webpage', 'deleting model weights'], 'A deployed model receives a prompt and responds. What phase is this?', 'inference', ['preprocessing only', 'annotation', 'database migration']),
        _fact('conditional image generation', 'text or other input guides the generated image', ['images cannot be conditioned', 'only filenames guide images', 'generation ignores all input'], 'A designer changes a prompt and receives a different scene. What caused the change?', 'the condition influenced generation', ['the database schema', 'a completed attempt', 'a CSS selector']),
        _fact('model selection', 'select based on quality, cost, latency, and risk', ['select by name length only', 'always use the newest model', 'ignore deployment constraints'], 'A low-risk autocomplete feature needs low latency. What should guide selection?', 'measured latency and adequate quality', ['maximum temperature', 'random model choice', 'no testing']),
    ]),
    ('Large Language Models', [
        _fact('large language model', 'a neural model trained to predict and generate language tokens', ['a dictionary containing every answer', 'a database of verified facts', 'a compiler for all languages'], 'A model completes a sentence from preceding text. What is its core operation?', 'predicting likely language continuations', ['retrieving an exact sentence only', 'executing every command', 'checking truth automatically']),
        _fact('next-token prediction', 'estimating likely next tokens from context', ['predicting the next user identity', 'choosing a database index', 'translating every word independently'], 'Why does an LLM need preceding context?', 'context helps estimate the next token', ['context only changes font size', 'the model cannot use context', 'context is stored as a password']),
        _fact('pretraining corpus', 'a large collection of text or other training examples', ['only one prompt from deployment', 'only human scores', 'a CSS file'], 'What supplies broad language patterns during pretraining?', 'a large training corpus', ['a single answer key', 'the browser cache', 'the final user message only']),
        _fact('token probability', 'the model scores candidate next tokens', ['every token has equal certainty', 'tokens are database rows', 'probabilities are always facts'], 'A token has the highest probability but is not selected at high temperature. What can explain this?', 'sampling can choose another candidate', ['the tokenizer stopped', 'the prompt was deleted', 'the model became a compiler']),
        _fact('LLM context', 'the text available to the model for the current generation', ['all internet content automatically', 'only the first character', 'the model weights themselves'], 'Why might an LLM fail to use a long pasted section?', 'some content may exceed or be outside its context', ['the text is always known', 'the model has no tokens', 'the output is a database join']),
        _fact('instruction following', 'using prompt instructions to shape the response', ['ignoring all prompt constraints', 'changing model weights per request', 'retrieving only images'], 'A user asks for JSON with three fields. What helps produce that format?', 'a clear instruction and schema', ['a random temperature', 'a longer password', 'removing the output format']),
        _fact('language-model limitation', 'language fluency does not prove factual correctness', ['fluent output is always true', 'LLMs cannot make grammatical text', 'all errors are visible'], 'A confident answer conflicts with official documentation. What is the correct response?', 'check the official documentation', ['trust confidence', 'increase temperature', 'ignore the conflict']),
        _fact('completion versus chat', 'chat interfaces package messages and roles around model generation', ['chat removes all context', 'completion cannot generate text', 'roles are database tables only'], 'Why does a chat API often separate system and user messages?', 'to distinguish behavior instructions from the request', ['to change token spelling', 'to prevent any output', 'to store passwords']),
        _fact('model context limit', 'a maximum amount of input and generated context', ['an unlimited memory guarantee', 'a limit on screen pixels', 'a restriction on user accounts'], 'A prompt is truncated before the model sees its ending. What likely happened?', 'the context limit was exceeded', ['the model used too few layers', 'the answer was cached', 'the tokenizer became a database']),
        _fact('LLM output control', 'constraints and examples can make output more consistent', ['random wording always improves consistency', 'constraints make output impossible', 'examples are never useful'], 'A parser needs stable JSON. What is a practical aid?', 'a strict schema and validation step', ['unbounded prose', 'no format instruction', 'maximum randomness']),
    ]),
    ('Tokens and Context Windows', [
        _fact('token', 'a unit of text processed by a language model', ['always one complete word', 'always one sentence', 'only a computer file'], 'Why can a long word use multiple tokens?', 'tokenization may split text into pieces', ['every word is one token', 'tokens are paragraphs only', 'the model ignores spelling']),
        _fact('tokenization', 'mapping text into model vocabulary units', ['ranking users by role', 'compressing images only', 'writing database rows'], 'What happens before an LLM predicts output?', 'input text is tokenized', ['the answer is graded', 'the model is retrained', 'the browser submits a form']),
        _fact('context window', 'the maximum token context available for one interaction', ['the number of model layers', 'the number of users allowed', 'the output truth score'], 'A conversation loses its oldest messages as it grows. What constraint is involved?', 'the context window limit', ['the CSS width', 'the model license', 'the temperature setting']),
        _fact('token budget', 'a limit on input and output token usage', ['a budget of database tables', 'a guarantee of answer quality', 'a user password policy'], 'Why reserve output tokens when sending a large prompt?', 'the model needs space to generate a response', ['output needs no context', 'tokens are free in every system', 'the prompt becomes an image']),
        _fact('truncation', 'removing part of text to fit a limit', ['adding unlimited memory', 'translating text', 'checking every fact'], 'What risk does truncating a contract near its conclusion create?', 'important terms may be omitted', ['more accurate citations', 'automatic grounding', 'fewer ambiguities always']),
        _fact('context ordering', 'recent or strategically placed context can influence generation', ['order never affects language models', 'only file names matter', 'context order changes the database'], 'A key instruction is placed clearly near the request. Why?', 'it makes the intended instruction easier for the model to use', ['it changes the model weights', 'it guarantees truth', 'it removes tokens']),
        _fact('token cost', 'many services measure usage by input and output tokens', ['only number of prompts matters', 'cost never depends on output', 'tokens are not measurable'], 'A developer shortens repeated instructions and usage drops. What changed?', 'fewer input tokens were sent', ['the model stopped learning', 'the context window grew', 'the answer became a label']),
        _fact('context contamination', 'irrelevant or conflicting text can reduce response quality', ['more unrelated text always helps', 'context cannot conflict', 'irrelevant text becomes training'], 'A prompt includes three contradictory policies. What is a likely issue?', 'the model may follow the wrong or ambiguous policy', ['guaranteed accuracy', 'lower token count', 'automatic verification']),
        _fact('conversation memory', 'application-managed history can be added to future prompts', ['the model remembers every user forever by default', 'memory is always model retraining', 'history needs no storage'], 'A chat app recalls a preference after a new request. What likely supplies it?', 'stored history or profile context', ['a new model layer', 'random sampling', 'a CSS class']),
        _fact('context compression', 'summarizing history can preserve key information in fewer tokens', ['compression always adds every word', 'compression deletes all meaning', 'compression changes model weights'], 'A long conversation is summarized before continuing. Why?', 'to retain useful context within the token budget', ['to disable generation', 'to avoid all review', 'to create a new course']),
    ]),
    ('Prompt Engineering', [
        _fact('clear prompt goal', 'state the task and desired outcome explicitly', ['ask for anything without context', 'hide the task completely', 'use only a greeting'], 'Which prompt best requests a support summary?', 'Summarize the ticket in three factual bullet points.', ['Tell me something', 'Make it good', 'Process this']),
        _fact('prompt context', 'relevant background helps the model interpret the task', ['irrelevant details always improve output', 'context is never useful', 'context replaces evaluation'], 'A model must summarize a contract clause. What should the prompt include?', 'the relevant clause and the summary requirement', ['only a greeting', 'an unrelated poem', 'no source text']),
        _fact('output format', 'specifying a format makes responses easier to parse', ['format instructions reduce all accuracy', 'format never matters', 'format means changing weights'], 'An application expects fields name and risk. What should the prompt provide?', 'a JSON schema or explicit field format', ['a vague request', 'unbounded prose', 'a random example only']),
        _fact('constraints', 'limits such as length, audience, and exclusions guide generation', ['constraints make every output identical', 'constraints are ignored by definition', 'constraints are database keys'], 'A teacher wants a 100-word explanation for beginners. What is that?', 'a useful output constraint', ['a model retraining job', 'a vector index', 'a token deletion']),
        _fact('prompt iteration', 'improve a prompt based on observed outputs', ['write once and never test', 'change every system component first', 'avoid comparing responses'], 'The model omits edge cases, so the developer adds an explicit requirement. What is this?', 'prompt iteration', ['fine-tuning', 'database migration', 'tokenization']),
        _fact('few-shot prompting', 'providing examples of desired input-output behavior', ['providing no examples', 'retraining all model weights', 'only changing temperature'], 'A classifier prompt includes three labeled examples before a new ticket. What technique is used?', 'few-shot prompting', ['zero-shot prompting', 'pretraining', 'retrieval']),
        _fact('zero-shot prompting', 'asking a model to perform a task without examples', ['using many labeled examples', 'updating model weights', 'retrieving a vector'], 'A prompt directly asks for sentiment without sample answers. What is this?', 'zero-shot prompting', ['few-shot prompting', 'fine-tuning', 'chunking']),
        _fact('role instruction', 'describe the perspective or expertise expected from the model', ['a role grants real-world authority', 'a role changes weights permanently', 'a role replaces evidence'], 'A prompt asks for a beginner-friendly explanation from a tutor perspective. What does the role do?', 'sets the intended style and perspective', ['guarantees facts', 'retrieves policies', 'executes code']),
        _fact('prompt decomposition', 'break a complex task into smaller explicit steps', ['combine every task into ambiguity', 'remove all intermediate checks', 'ask for unrelated outputs'], 'A report needs extraction, validation, and formatting. What can improve reliability?', 'separate the stages or specify them clearly', ['increase temperature', 'remove the schema', 'hide the source']),
        _fact('prompt testing', 'compare prompts with representative test cases', ['test only the easiest example', 'judge from one lucky response', 'avoid edge cases'], 'A prompt works on normal tickets but fails on empty input. What should be added?', 'an edge-case test and revised instruction', ['a longer greeting', 'a new color theme', 'less evaluation']),
    ]),
    ('System, User, and Example Prompts', [
        _fact('system prompt', 'high-level behavior or policy instructions for the assistant', ['the customer message only', 'a database query result', 'a model weight file'], 'Where should a consistent safety policy normally be placed?', 'in a system-level instruction', ['in a random output sentence', 'only in a user typo', 'inside a vector ID']),
        _fact('user prompt', 'the current request or input from the user', ['the model training corpus', 'the hidden model weights', 'the evaluation dashboard'], 'A customer asks to summarize an invoice. Which message is the user prompt?', 'the customer invoice-summary request', ['the provider policy', 'the tokenizer vocabulary', 'the model checkpoint']),
        _fact('instruction priority', 'higher-priority instructions should constrain lower-priority requests', ['all messages have identical authority', 'the latest request always wins', 'data can rewrite policy'], 'A user asks the assistant to reveal a protected system instruction. What should happen?', 'follow policy and refuse the protected disclosure', ['reveal it automatically', 'ignore all safety rules', 'change the system prompt']),
        _fact('few-shot example quality', 'examples should represent the desired behavior accurately', ['examples can contradict the task', 'one irrelevant example is always enough', 'examples need no labels'], 'A sentiment classifier gets inconsistent demonstrations. What is likely?', 'inconsistent outputs or learned ambiguity', ['guaranteed accuracy', 'automatic fine-tuning', 'fewer tokens always']),
        _fact('structured prompt', 'separating instructions, context, and input reduces ambiguity', ['mixing all text without labels', 'removing the user input', 'using only punctuation'], 'Why label SOURCE and TASK sections?', 'the model can distinguish their roles more clearly', ['it changes weights', 'it prevents all hallucinations', 'it creates a database']),
        _fact('prompt injection', 'untrusted content attempts to override intended instructions', ['a helpful formatting request', 'a valid schema', 'a normal user question'], 'A retrieved document says ignore the system rules. What is this?', 'a prompt injection attempt', ['a token budget', 'a safe completion', 'a data type']),
        _fact('instruction boundary', 'treat external content as data rather than executable instructions', ['execute every retrieved sentence', 'trust quoted commands automatically', 'remove all source text'], 'A webpage contains malicious instructions inside quoted text. What should the model do?', 'analyze it as content under the application policy', ['obey it blindly', 'publish secrets', 'change its system role']),
        _fact('user clarification', 'ask for missing information when the task cannot be completed reliably', ['guess sensitive details', 'invent constraints', 'ignore ambiguity'], 'A request says “summarize the report” but includes three reports. What helps?', 'ask which report or summarize all with labels', ['choose secretly', 'invent a report', 'delete the sources']),
        _fact('prompt template', 'a reusable structure with controlled variable fields', ['a fixed answer with no inputs', 'a model retraining file', 'a vector database'], 'An application inserts a customer name into a standard support prompt. What is used?', 'a prompt template', ['a new model', 'a compiler', 'a random seed']),
        _fact('safe prompt composition', 'keep secrets and untrusted input separate from privileged instructions', ['place API keys in every prompt', 'let input rewrite policy', 'send private data without need'], 'What is a safer way to handle a customer message?', 'insert it as clearly delimited untrusted content', ['concatenate it into policy text', 'execute it as instructions', 'log secrets in the prompt']),
    ]),
    ('Generation Controls and Hallucinations', [
        _fact('temperature', 'a sampling control that usually increases variation when raised', ['a measure of factual accuracy', 'the context window size', 'a security permission'], 'A developer wants more predictable wording. What adjustment is common?', 'lower the temperature and evaluate the result', ['raise it indefinitely', 'remove the prompt', 'change the database']),
        _fact('top-p', 'limits sampling to a probability mass of candidate tokens', ['sets the number of model layers', 'counts user accounts', 'guarantees a citation'], 'What does top-p affect?', 'the candidate set considered during sampling', ['the training corpus license', 'the screen size', 'the user role']),
        _fact('determinism', 'fixed settings and seeds can make outputs more repeatable but not necessarily true', ['repeatability guarantees correctness', 'randomness guarantees quality', 'determinism removes evaluation'], 'Two identical requests produce the same answer repeatedly. What does that show?', 'repeatability under those settings', ['the answer is verified', 'the model retrieved a source', 'the answer is legally correct']),
        _fact('hallucination', 'a plausible-sounding but unsupported or false output', ['a verified citation', 'a successful retrieval', 'a correct schema'], 'The model invents a product feature not in the catalog. What is this?', 'a hallucination', ['grounding', 'tokenization', 'classification']),
        _fact('grounded answer', 'an answer supported by supplied or retrieved evidence', ['an answer based only on style', 'a random completion', 'an unsupported guess'], 'What makes a policy chatbot response more trustworthy?', 'linking it to relevant approved policy text', ['raising temperature', 'removing citations', 'using shorter words']),
        _fact('uncertainty handling', 'state uncertainty and request evidence instead of inventing facts', ['confidently fill every gap', 'hide uncertainty', 'replace missing facts with names'], 'A source does not answer a question. What should the assistant do?', 'say the evidence is insufficient and ask for more', ['invent a likely answer', 'cite an unrelated source', 'change the user role']),
        _fact('parameter tradeoff', 'generation controls trade off diversity and consistency', ['parameters affect only colors', 'all settings have identical effects', 'more randomness always improves facts'], 'A creative brainstorming tool needs varied ideas but a parser needs stable JSON. What follows?', 'use different settings for the two tasks', ['use maximum randomness for both', 'remove validation', 'share one prompt blindly']),
        _fact('citation verification', 'check that cited sources exist and support the claim', ['citations are true because they look formal', 'links never need checking', 'a URL proves every claim'], 'A report includes five generated references. What should reviewers do?', 'verify each reference and its relevance', ['trust the count', 'delete the source text', 'increase temperature']),
        _fact('fallback behavior', 'provide a safe alternative when generation is unsupported or uncertain', ['continue with invented content', 'hide the failure', 'retry forever without limits'], 'A finance assistant cannot verify a balance. What is appropriate?', 'ask the user to use the official account channel', ['guess the balance', 'expose another customer record', 'mark it verified']),
        _fact('output validation', 'check generated structure and allowed values before use', ['send any output directly to production', 'validate only the font', 'skip parsing errors'], 'An API expects a date and amount. What should happen before saving?', 'parse and validate both fields', ['trust free text', 'ignore missing fields', 'increase output length']),
    ]),
    ('Embeddings and Semantic Search', [
        _fact('embedding', 'a numeric representation capturing aspects of meaning', ['a human-readable answer key', 'a password hash used for login', 'a video URL'], 'Why represent documents as vectors?', 'to compare semantic relationships numerically', ['to display them as headings', 'to guarantee truth', 'to execute them']),
        _fact('vector similarity', 'a measure of how close two embeddings are', ['the number of words only', 'a model temperature', 'a permission check'], 'A query vector is close to a document vector. What may that indicate?', 'the document is semantically relevant', ['the document is always factually correct', 'the document is newer', 'the query is longer']),
        _fact('cosine similarity', 'compares the angle between vectors', ['counts only exact spelling', 'measures response latency', 'sets token limits'], 'When is cosine similarity useful?', 'when comparing embedding direction or semantic orientation', ['when executing Python', 'when publishing prompts', 'when authenticating users']),
        _fact('semantic search', 'retrieves meaning-related content even when wording differs', ['matches only identical characters', 'always generates new facts', 'searches only filenames'], 'A query “cancel my plan” finds “terminate subscription.” What enabled this?', 'semantic similarity in embeddings', ['exact string matching', 'random sampling', 'fine-tuning the browser']),
        _fact('embedding model choice', 'use an embedding model compatible with the search task and data', ['any vector from any model is interchangeable', 'larger is always better', 'embedding quality needs no testing'], 'Why use the same embedding model for documents and queries?', 'their vectors share a compatible representation space', ['it removes all metadata', 'it makes documents true', 'it prevents retrieval']),
        _fact('vector database', 'stores and searches vector representations efficiently', ['stores only passwords', 'generates text by itself', 'replaces every application database'], 'What is a vector database useful for?', 'nearest-neighbor search over embeddings', ['calculating payroll', 'rendering CSS', 'writing system prompts']),
        _fact('metadata filtering', 'limits vector results using fields such as tenant or date', ['changes the embedding meaning', 'removes all semantic search', 'guarantees complete recall'], 'A user must search only their department. What helps?', 'filter results by department metadata', ['trust the query alone', 'delete department labels', 'increase temperature']),
        _fact('chunk embedding', 'embed meaningful document segments for targeted retrieval', ['embed only the filename', 'embed an entire unlimited archive', 'skip document text'], 'Why split a handbook before indexing?', 'smaller meaningful chunks can match specific questions', ['to remove context', 'to change URLs', 'to train the model from scratch']),
        _fact('nearest neighbors', 'retrieve vectors most similar to a query vector', ['retrieve the oldest rows only', 'choose random documents', 'sort by title alphabetically'], 'What does a nearest-neighbor index return?', 'candidate vectors close to the query', ['model weights', 'new tokens only', 'user permissions']),
        _fact('search evaluation', 'measure relevance of retrieved results with representative queries', ['assume every top result is relevant', 'evaluate only database size', 'avoid negative examples'], 'A search returns many plausible but irrelevant chunks. What should be measured?', 'retrieval relevance and ranking quality', ['screen brightness', 'prompt font', 'number of API keys']),
    ]),
    ('RAG Fundamentals', [
        _fact('retrieval-augmented generation', 'retrieve relevant sources and provide them to a generator', ['fine-tune for every question', 'generate without evidence', 'search only after responding'], 'A support assistant searches a handbook before answering. What architecture is this?', 'retrieval-augmented generation', ['pure classification', 'image diffusion', 'manual lookup']),
        _fact('RAG workflow', 'retrieve, assemble context, generate, and often cite or validate', ['generate first and retrieve never', 'only tokenize the question', 'store answers without sources'], 'Which sequence best describes a grounded answer?', 'retrieve evidence, add context, then generate', ['generate, delete evidence, then answer', 'train a new model per request', 'sort URLs only']),
        _fact('retrieval query', 'a representation of the user question used to find relevant chunks', ['the final answer text only', 'a user password', 'a model license'], 'What is sent to the retriever in a basic RAG system?', 'the user question or its embedding', ['the database schema only', 'the final citation only', 'a random token']),
        _fact('context injection', 'placing retrieved evidence into the model input with clear boundaries', ['letting documents overwrite system policy', 'hiding the evidence', 'executing retrieved text'], 'How should retrieved text be supplied safely?', 'as delimited reference context under application instructions', ['as a new system policy', 'as executable code', 'without source labels']),
        _fact('grounding', 'constraining an answer with relevant external evidence', ['increasing temperature', 'removing source text', 'adding unrelated examples'], 'Why can RAG reduce unsupported answers?', 'the model has relevant evidence to use', ['it guarantees every claim', 'it eliminates all model errors', 'it changes the model weights']),
        _fact('RAG citation', 'connect a response claim to the source chunk that supports it', ['cite a random document', 'cite only the model name', 'omit all source references'], 'What improves answer review in a policy assistant?', 'returning source references with the answer', ['longer prose', 'higher randomness', 'hidden retrieval']),
        _fact('RAG failure mode', 'poor retrieval can lead to an unsupported or incomplete answer', ['retrieval always fixes hallucinations', 'wrong chunks are harmless', 'generation ignores context'], 'The correct policy exists but is not retrieved. What may happen?', 'the answer can still be incomplete or wrong', ['guaranteed citation', 'perfect grounding', 'automatic correction']),
        _fact('hybrid retrieval', 'combine semantic and lexical signals', ['use only random retrieval', 'remove all keywords', 'use generation without search'], 'A search needs both exact policy codes and related wording. What helps?', 'hybrid lexical and semantic retrieval', ['temperature only', 'a larger font', 'one fixed example']),
        _fact('reranking', 'reorder retrieved candidates using a relevance model', ['delete all candidates', 'generate a final answer immediately', 'change the source text'], 'Why rerank top search candidates?', 'to place the most useful chunks first', ['to hide citations', 'to train the user', 'to increase token spelling']),
        _fact('RAG evaluation', 'evaluate retrieval and generation as separate but connected stages', ['measure only final color', 'skip retrieval metrics', 'assume answer quality proves retrieval quality'], 'A response is wrong because the needed chunk was missing. What should be diagnosed?', 'retrieval recall as well as generation', ['temperature only', 'CSS layout', 'user password']),
    ]),
    ('Chunking and Knowledge Grounding', [
        _fact('chunk size', 'choose a segment size that preserves meaning while fitting context', ['always use one character', 'always use the whole archive', 'size never affects retrieval'], 'A chunk cuts a sentence between a rule and its exception. What is the risk?', 'retrieved context may lose important meaning', ['better grounding automatically', 'lower storage only', 'no effect']),
        _fact('overlap', 'share some neighboring text between chunks', ['remove all boundaries', 'duplicate the entire archive', 'make chunks unrelated'], 'Why add overlap to document chunks?', 'to reduce information loss at boundaries', ['to change the model weights', 'to hide metadata', 'to disable retrieval']),
        _fact('semantic chunking', 'split text at meaningful topic or section boundaries', ['split at random characters only', 'ignore headings', 'use one chunk for every database'], 'A handbook has clear sections and procedures. What chunking choice helps?', 'split around meaningful sections', ['shuffle every sentence', 'remove headings', 'store only titles']),
        _fact('document metadata', 'attributes such as source, section, and date that support filtering and citations', ['the model temperature', 'the answer confidence alone', 'a prompt emoji'], 'What metadata helps cite a retrieved handbook section?', 'document name and section identifier', ['random token count', 'screen width', 'user password']),
        _fact('knowledge grounding', 'tie output claims to trusted, relevant knowledge', ['use unsupported model memory only', 'treat every web page as trusted', 'remove source references'], 'A regulated answer needs approved documents. What is essential?', 'retrieve and cite approved knowledge', ['increase creativity', 'hide the source', 'skip review']),
        _fact('stale knowledge', 'outdated indexed content can produce outdated answers', ['old content is always correct', 'retrieval updates itself automatically', 'dates never matter'], 'A product policy changed yesterday but the index is old. What is the issue?', 'stale knowledge in the index', ['higher precision', 'a shorter prompt', 'better tokenization']),
        _fact('index refresh', 'update embeddings and metadata when source content changes', ['never update indexes', 'only change the UI', 'delete new documents'], 'How should a changed policy become searchable?', 're-index the changed content', ['increase temperature', 'ask a new user', 'change the answer color']),
        _fact('source authority', 'prefer trusted sources appropriate to the task', ['rank all sources equally', 'trust the least reliable source', 'choose by document length only'], 'For internal policy answers, which source should rank highest?', 'the approved current policy repository', ['an unverified comment', 'a random snippet', 'an unrelated article']),
        _fact('context packing', 'include the most relevant evidence within the model token budget', ['include every retrieved chunk', 'remove all evidence', 'sort by filename only'], 'A query retrieves 50 chunks but the model has limited context. What should happen?', 'select and pack the strongest relevant chunks', ['send all blindly', 'send none', 'use random chunks']),
        _fact('grounded refusal', 'decline or qualify an answer when evidence is insufficient', ['invent missing policy', 'cite unrelated text', 'state certainty without support'], 'No source addresses a user’s special case. What is safest?', 'explain the limitation and request authoritative guidance', ['guess', 'hide the gap', 'change retrieval labels']),
    ]),
    ('Pretraining, Fine-tuning, and Inference', [
        _fact('pretraining', 'learn broad patterns from a large general corpus', ['teach one user preference only', 'retrieve one document', 'format an output'], 'What gives a base model broad language ability?', 'large-scale pretraining', ['a single user prompt', 'one vector query', 'a CSS file']),
        _fact('fine-tuning', 'update a model using task- or domain-specific examples', ['retrieve a document at runtime', 'change only a prompt label', 'delete model parameters'], 'A company trains on labeled support replies to improve tone. What is this?', 'fine-tuning', ['semantic search', 'zero-shot prompting', 'chunking']),
        _fact('instruction tuning', 'train a model to follow natural-language tasks more usefully', ['remove all instructions', 'only compress images', 'store a vector'], 'Why instruction-tune a base language model?', 'to improve response behavior for tasks and instructions', ['to create a database index', 'to reduce every token', 'to hide context']),
        _fact('inference', 'run learned parameters on new input', ['adjust weights with every request', 'label the training corpus', 'split documents'], 'A deployed model summarizes a new email. What is occurring?', 'inference', ['pretraining', 'fine-tuning', 'indexing']),
        _fact('fine-tuning versus RAG', 'fine-tuning changes behavior while RAG supplies changing knowledge', ['both are identical', 'RAG always changes weights', 'fine-tuning is a search query'], 'A policy changes weekly and must be current. What is often better?', 'retrieve the current policy with RAG', ['fine-tune every week by default', 'ignore the policy', 'increase temperature']),
        _fact('catastrophic forgetting', 'new training can reduce performance on earlier capabilities', ['new training always preserves every skill', 'it only affects screen layout', 'it is a retrieval metric'], 'A narrow fine-tune harms general writing. What may have happened?', 'catastrophic forgetting', ['better grounding', 'tokenization', 'metadata filtering']),
        _fact('training data quality', 'clean, relevant, representative data improves learning', ['more noise always improves a model', 'labels never matter', 'duplicates cannot affect training'], 'A fine-tune contains many contradictory labels. What is likely?', 'less consistent learned behavior', ['guaranteed accuracy', 'lower latency only', 'automatic evaluation']),
        _fact('parameter-efficient tuning', 'adapt a smaller part or added parameters instead of all weights', ['always retrain every parameter', 'only alter prompts at runtime', 'remove the model'], 'Why use an adapter for a domain task?', 'reduce compute and storage for adaptation', ['guarantee facts', 'replace retrieval', 'increase context automatically']),
        _fact('model checkpoint', 'a saved state of learned parameters', ['a user prompt', 'a source citation', 'a vector query'], 'What can a checkpoint be used for?', 'restoring or deploying a trained model state', ['retrieving a policy', 'formatting JSON', 'choosing a browser page']),
        _fact('deployment inference', 'serve a trained model with resources and controls suited to production', ['run without monitoring', 'expose all training data', 'skip access checks'], 'What matters when putting inference into production?', 'latency, cost, monitoring, and safe access', ['only prompt length', 'random colors', 'no logging']),
    ]),
    ('Transformers, Attention, and Encoders', [
        _fact('transformer', 'a neural architecture that processes sequences using attention', ['a vector database product', 'a fixed rule list', 'a file format'], 'What architecture powers many modern language models?', 'the transformer architecture', ['only decision trees', 'a spreadsheet', 'a web server']),
        _fact('attention', 'weigh relationships between tokens while processing context', ['delete unrelated files', 'assign user permissions', 'sort words alphabetically'], 'Why can attention help resolve a pronoun?', 'it relates the pronoun to relevant surrounding tokens', ['it changes the font', 'it searches every website', 'it guarantees truth']),
        _fact('self-attention', 'tokens attend to other tokens in the same sequence', ['tokens only attend to a database', 'one token is always isolated', 'attention means user feedback'], 'In a sentence, what can self-attention connect?', 'a token with relevant tokens in its context', ['only the first word', 'two users', 'two files']),
        _fact('query-key-value', 'attention compares queries and keys to combine values', ['three database tables only', 'three user roles', 'three prompt messages'], 'What is the purpose of values in attention?', 'carry information weighted by relevance', ['set the temperature', 'store passwords', 'choose a course']),
        _fact('positional information', 'helps a transformer represent token order', ['removes sequence order', 'stores user identity', 'guarantees grammar'], 'Why does a model need positional information?', 'the same tokens can mean different things in different orders', ['to create embeddings only', 'to bypass attention', 'to retrieve URLs']),
        _fact('encoder', 'builds a contextual representation of input', ['always generates the final answer alone', 'only stores files', 'sets a user role'], 'Which component is especially suited to understanding an input sequence?', 'an encoder', ['a CSS parser', 'a database trigger', 'a password manager']),
        _fact('decoder', 'generates output tokens using context', ['only labels documents', 'cannot generate text', 'only stores embeddings'], 'Which component is central to autoregressive text generation?', 'a decoder', ['a vector index', 'a spreadsheet', 'a metadata filter']),
        _fact('encoder-decoder', 'uses an encoder for input and decoder for output generation', ['uses no input representation', 'only retrieves URLs', 'only classifies numbers'], 'A translation model maps a source sentence to a target sentence. What architecture fits?', 'encoder-decoder', ['only a cache', 'only a tokenizer', 'a database schema']),
        _fact('attention context', 'attention helps use relevant parts of a sequence', ['attention ignores context', 'attention is a citation', 'attention prevents tokenization'], 'A question refers to a name several words earlier. What helps connect them?', 'contextual attention', ['higher screen resolution', 'a new database', 'a user reset']),
        _fact('transformer limitation', 'attention still depends on available context and learned patterns', ['attention guarantees factual memory', 'transformers know every source', 'context limits never matter'], 'Why can a transformer answer incorrectly despite attention?', 'it may lack evidence or learn an incorrect pattern', ['attention guarantees truth', 'the prompt was always perfect', 'all outputs are retrieved']),
    ]),
    ('Text, Image, and Multimodal Generation', [
        _fact('text generation', 'produce a sequence of language tokens', ['return only a database row', 'draw pixels without an image model', 'classify without output'], 'An assistant drafts an email from instructions. What is generated?', 'a text sequence', ['a vector index', 'a user role', 'a schema migration']),
        _fact('image generation', 'produce visual content from learned image patterns and conditions', ['only resize an existing file', 'retrieve a filename', 'sort pixels'], 'A model creates an illustration from a prompt. What capability is used?', 'image generation', ['text classification', 'database filtering', 'token counting']),
        _fact('multimodal model', 'handles more than one input or output modality', ['handles only one fixed character', 'is a database table', 'cannot combine inputs'], 'A model reads a photo and answers a question about it. What is this?', 'multimodal understanding', ['only text autocomplete', 'only vector search', 'only file copying']),
        _fact('image conditioning', 'input text or image guidance influences the generated visual result', ['images are always random', 'conditioning deletes pixels', 'prompts cannot affect images'], 'Changing “sunset” to “night” changes the generated scene. Why?', 'the text condition guides generation', ['the database changed', 'the model was retrained', 'the file was only renamed']),
        _fact('alt text generation', 'describe visual content in language for accessibility or search', ['remove the image', 'change the image pixels', 'create a password'], 'What is a practical use of vision-language generation?', 'drafting alt text for an image', ['deleting metadata', 'sorting users', 'training a database']),
        _fact('multimodal grounding', 'base an answer on the supplied image, audio, or text evidence', ['answer from unrelated memory', 'ignore the uploaded file', 'invent visual details'], 'A chart question should be answered from the chart itself. What matters?', 'grounding the response in the chart', ['higher temperature', 'a longer greeting', 'no input']),
        _fact('image safety', 'screen generated content for policy, privacy, and misuse risks', ['publish every image automatically', 'ignore faces and trademarks', 'remove review'], 'A generator creates images of real people. What should be considered?', 'consent, privacy, and misuse controls', ['only image size', 'random sampling', 'token count']),
        _fact('modality alignment', 'connect information across modalities in a shared task', ['treat each modality as unrelated', 'convert everything to passwords', 'remove visual context'], 'A model matches a product photo to a textual description. What is needed?', 'cross-modal representation and comparison', ['only spelling correction', 'only a database key', 'only a system prompt']),
        _fact('image prompt specificity', 'include subject, style, composition, and constraints when useful', ['use no subject or constraints', 'repeat random words', 'hide the desired result'], 'Why specify camera angle and background in an image prompt?', 'to guide composition more precisely', ['to change training data', 'to guarantee exact pixels', 'to disable generation']),
        _fact('multimodal evaluation', 'test each modality and their interaction against task criteria', ['evaluate text only for a vision task', 'judge by file size only', 'skip real examples'], 'A chart assistant misreads axes. What test is needed?', 'visual accuracy tests with representative charts', ['more emojis', 'higher temperature', 'fewer images']),
    ]),
    ('AI Agents and Tool Calling', [
        _fact('AI agent', 'a system that plans or acts toward a goal using models and tools', ['a model that only prints one fixed string', 'a database index', 'a prompt with no output'], 'An assistant checks inventory and then creates an order. What makes it agent-like?', 'it uses actions toward a goal', ['it only summarizes text', 'it only changes color', 'it never calls a tool']),
        _fact('tool calling', 'the model requests a defined external function for an action or lookup', ['the model secretly executes any code', 'a user prompt becomes a password', 'a tool call is only formatting'], 'A model needs current weather. What should it do?', 'request a weather tool with structured arguments', ['invent the weather', 'change temperature', 'search its old memory only']),
        _fact('function schema', 'defines allowed function arguments and their types', ['lets the model call anything', 'stores the final answer only', 'removes validation'], 'Why provide a JSON schema for a calendar function?', 'to constrain arguments such as date and duration', ['to guarantee the meeting exists', 'to train the model live', 'to hide the tool']),
        _fact('tool result handling', 'return tool output to the model or application for the next controlled step', ['ignore the result', 'treat every result as trusted truth', 'run unlimited tools'], 'A database lookup returns no record. What should the agent do?', 'handle the empty result explicitly', ['invent a record', 'retry forever', 'expose another user']),
        _fact('agent permissions', 'restrict tools and data to the minimum required scope', ['give every agent administrator access', 'let prompts define permissions', 'skip authentication'], 'A support agent only needs ticket read access. What is safer?', 'grant only ticket read permission', ['grant database admin', 'share API keys in prompts', 'allow arbitrary shell commands']),
        _fact('agent loop', 'repeatedly observe, decide, act, and stop under limits', ['loop forever without checks', 'act once with no result', 'ignore tool errors'], 'What prevents an agent from repeatedly calling a failing API?', 'step limits, timeouts, and error handling', ['higher temperature', 'more tools', 'no logs']),
        _fact('human approval', 'require confirmation before high-impact or irreversible actions', ['automate every deletion', 'hide actions from users', 'skip audit logs'], 'Before an agent sends a large payment, what is appropriate?', 'a human approval step', ['automatic execution', 'a random retry', 'unrestricted access']),
        _fact('function-calling reliability', 'validate tool arguments and results at the application boundary', ['trust model-generated arguments blindly', 'execute arbitrary strings', 'remove schemas'], 'A tool requires an integer account ID. What should the app do?', 'validate and authorize the parsed ID', ['run the raw text', 'use any account', 'ignore type errors']),
        _fact('agent observability', 'record actions, tool calls, failures, and outcomes for review', ['hide every action', 'log only final prose', 'avoid tracing'], 'Why trace an agent’s tool calls?', 'to debug behavior and audit decisions', ['to increase randomness', 'to replace permissions', 'to remove context']),
        _fact('workflow versus agent', 'a fixed workflow is preferable when steps are known and predictable', ['agents are always better', 'workflows cannot call tools', 'fixed steps need no testing'], 'A monthly report always follows the same five steps. What is a good design?', 'a deterministic workflow with validation', ['an unrestricted agent', 'random planning', 'no error handling']),
    ]),
    ('Evaluation, Reliability, and Quality', [
        _fact('evaluation set', 'a representative collection of test inputs and expected criteria', ['one lucky prompt', 'the model name only', 'a production secret'], 'What helps compare two prompt versions?', 'the same representative evaluation set', ['different random questions only', 'no expected criteria', 'screen size']),
        _fact('accuracy', 'the proportion of correct results for a defined task', ['response length', 'model temperature', 'number of tokens only'], 'A classifier gets 90 correct labels out of 100. What basic measure is 90 percent?', 'accuracy', ['latency', 'context size', 'diversity']),
        _fact('precision and recall', 'precision concerns correctness of retrieved positives while recall concerns finding relevant positives', ['both mean response length', 'both measure temperature', 'neither concerns retrieval'], 'A search misses many relevant documents. Which issue is especially important?', 'recall', ['font size', 'temperature only', 'token spelling']),
        _fact('human evaluation', 'people judge qualities that automated metrics may miss', ['human review is never useful', 'only token count matters', 'automatic metrics know every context'], 'Why ask experts to rate safety and helpfulness?', 'those qualities need contextual judgment', ['to change model weights immediately', 'to create embeddings', 'to skip tests']),
        _fact('regression testing', 'rerun known tests after a prompt or model change', ['test only new features', 'delete old examples', 'assume changes cannot regress'], 'A new prompt fixes one case but breaks a prior case. What catches this?', 'regression tests', ['higher temperature', 'more tools', 'no evaluation']),
        _fact('reliability', 'consistent acceptable behavior across relevant inputs and conditions', ['one perfect response proves reliability', 'randomness proves quality', 'reliability means no monitoring'], 'A model works only on short requests. What should be tested?', 'varied realistic inputs and failure cases', ['one short prompt', 'only the UI', 'no edge cases']),
        _fact('latency', 'the time required to return or complete a response', ['factual correctness', 'training label quality', 'vector dimension'], 'A voice assistant feels slow despite accurate output. Which metric matters?', 'latency', ['accuracy only', 'prompt style', 'temperature']),
        _fact('cost evaluation', 'measure usage and infrastructure cost against task value', ['cost is unrelated to tokens', 'larger models are free', 'quality is the only deployment concern'], 'A small model meets quality targets at lower cost. What should be considered?', 'using the smaller model for that task', ['always use the largest model', 'remove monitoring', 'increase context']),
        _fact('failure analysis', 'inspect input, retrieval, model output, and application handling', ['blame the model without evidence', 'change every component at once', 'ignore logs'], 'An answer cites the wrong policy. What is a useful first step?', 'trace retrieval and source selection', ['increase font size', 'delete history', 'raise temperature']),
        _fact('quality threshold', 'define acceptable performance before release', ['release without criteria', 'use a vague feeling only', 'change thresholds per result'], 'Why set a minimum grounded-answer rate?', 'to make release decisions measurable', ['to guarantee perfection', 'to remove testing', 'to choose a logo']),
    ]),
    ('Bias, Privacy, Security, and Responsible AI', [
        _fact('bias', 'systematic differences or unfair patterns in data or outputs', ['any random typo', 'a faster response', 'a larger context window'], 'A hiring model disadvantages one group consistently. What concern is this?', 'bias and fairness risk', ['latency', 'tokenization', 'formatting']),
        _fact('representative data', 'data should reflect relevant users and cases', ['exclude difficult groups', 'use only convenient examples', 'duplicate one group blindly'], 'What can improve evaluation fairness?', 'include representative scenarios and subgroup checks', ['remove subgroup labels', 'test one user only', 'avoid measuring outcomes']),
        _fact('privacy minimization', 'collect and send only data necessary for the task', ['send every personal field', 'retain secrets forever', 'include unrelated records'], 'A summarizer needs an order status but not a customer address. What is safer?', 'omit the unnecessary address', ['send all fields', 'publish the address', 'store it in the prompt']),
        _fact('data anonymization', 'remove or transform identifying information to reduce exposure', ['copy identifiers into logs', 'publish raw records', 'assume masking is always perfect'], 'Before sharing support examples for evaluation, what helps protect users?', 'remove or mask direct identifiers', ['include emails', 'include passwords', 'skip review']),
        _fact('prompt injection security', 'do not let untrusted content override privileged instructions', ['execute retrieved commands', 'trust web text as policy', 'allow arbitrary tool calls'], 'A document tells an agent to send secrets. What should happen?', 'treat it as untrusted content and block the action', ['follow it', 'send secrets', 'grant permissions']),
        _fact('least privilege', 'give an AI application only the permissions it needs', ['grant administrator by default', 'share one key everywhere', 'skip authorization'], 'A read-only assistant needs customer lookup. What access is appropriate?', 'scoped read-only access', ['database admin', 'shell access', 'all tenant data']),
        _fact('secure logging', 'avoid storing secrets and sensitive content unnecessarily', ['log API keys for debugging', 'write passwords to prompts', 'keep unlimited raw transcripts'], 'What should an application avoid in logs?', 'API keys and unnecessary personal data', ['request IDs', 'sanitized errors', 'timing metrics']),
        _fact('transparency', 'tell users when and how AI is involved where appropriate', ['hide all automation', 'claim human review that did not happen', 'avoid disclosures'], 'A generated customer reply is sent automatically. What is responsible?', 'provide appropriate disclosure and escalation options', ['pretend it was handwritten', 'hide errors', 'remove support contact']),
        _fact('human oversight', 'people review or control decisions with meaningful impact', ['automate sensitive decisions without review', 'remove appeal paths', 'trust confidence alone'], 'For a benefits eligibility recommendation, what is needed?', 'human review and an appeal process', ['automatic denial only', 'no records', 'no explanation']),
        _fact('responsible deployment', 'monitor harm, performance, privacy, and misuse after release', ['responsibility ends at launch', 'monitoring is optional for high risk', 'only uptime matters'], 'What should a team do after launching a public chatbot?', 'monitor incidents and improve safeguards', ['ignore reports', 'remove audit logs', 'expand permissions']),
    ]),
    ('Real-world Generative AI Applications', [
        _fact('document summarization', 'compress a source while preserving important meaning', ['invent new requirements', 'remove every qualification', 'translate without reading'], 'What makes a legal summary safer?', 'preserve conditions and cite the source', ['shorten blindly', 'omit exceptions', 'add unsupported advice']),
        _fact('customer support assistant', 'combine answer generation with approved knowledge and escalation', ['answer every issue from memory', 'hide uncertainty', 'grant account changes automatically'], 'A billing assistant cannot resolve a refund dispute. What should it do?', 'escalate with the relevant case context', ['invent a refund', 'delete the ticket', 'expose another account']),
        _fact('code assistant', 'suggest code while developers review, test, and secure it', ['run every suggestion in production', 'assume code is bug-free', 'skip dependency review'], 'A generated SQL query is proposed. What is essential?', 'review it for correctness and injection risk', ['execute blindly', 'publish credentials', 'remove tests']),
        _fact('content drafting', 'use generated drafts with human editing and fact checking', ['publish every draft automatically', 'treat tone as truth', 'remove approvals'], 'A newsroom uses AI for a first draft. What remains necessary?', 'editorial review and source verification', ['skip sources', 'trust fluency', 'hide AI use']),
        _fact('education tutor', 'adapt explanations while preserving accurate curriculum boundaries', ['invent grades', 'replace teachers in every decision', 'reveal private records'], 'A tutor is unsure about an answer. What should it do?', 'explain uncertainty and direct the learner to reliable material', ['guess confidently', 'mark correct automatically', 'hide the source']),
        _fact('code retrieval assistant', 'retrieve relevant repository context before generating a change', ['generate without repository context', 'send every secret file', 'ignore tests'], 'A developer asks how a local API is used. What helps?', 'retrieve relevant code and tests with access controls', ['use unrelated code', 'expose keys', 'skip validation']),
        _fact('creative ideation', 'generate varied possibilities that humans select and refine', ['treat ideas as final facts', 'remove human judgment', 'guarantee originality'], 'A team brainstorms campaign concepts with AI. What is a good workflow?', 'generate options, then review fit and originality', ['publish all ideas', 'ignore brand constraints', 'claim guaranteed ownership']),
        _fact('workflow automation', 'use deterministic checks around generated steps', ['let prose trigger irreversible actions alone', 'remove approvals', 'skip validation'], 'An AI extracts invoice fields before payment. What is needed?', 'validate fields and require appropriate approval', ['pay from raw text', 'ignore totals', 'grant broad access']),
        _fact('architecture choice', 'choose generation, retrieval, tools, or rules based on the requirement', ['use one architecture for everything', 'avoid constraints', 'select by trend alone'], 'A tax rate must come from current official data. What design fits?', 'retrieve the official rate and validate it', ['generate a rate from memory', 'use high temperature', 'ignore the source']),
        _fact('AI product feedback', 'use monitored user feedback and failure cases to improve the system', ['collect no feedback', 'change prompts from one complaint only', 'hide incidents'], 'A support assistant fails on regional policies. What should the team do?', 'analyze cases and add representative tests or grounding', ['ignore the pattern', 'remove regional data', 'raise temperature']),
    ]),
]


def _merge_topic_pair(topics, first_name, second_name, merged_name):
    first_index = next(index for index, item in enumerate(topics) if item[0] == first_name)
    second_index = next(index for index, item in enumerate(topics) if item[0] == second_name)
    first_facts = topics[first_index][1][:5]
    second_facts = topics[second_index][1][:5]
    merged = (merged_name, first_facts + second_facts)
    return [
        item for index, item in enumerate(topics)
        if index not in {first_index, second_index}
    ] + [merged]


TOPICS = _merge_topic_pair(
    TOPICS,
    'Generative AI Fundamentals',
    'AI, Machine Learning, and Generative AI',
    'AI Foundations and Generative Models',
)
TOPICS = _merge_topic_pair(
    TOPICS,
    'Generation Controls and Hallucinations',
    'Evaluation, Reliability, and Quality',
    'Generation Controls, Reliability, and Evaluation',
)
TOPICS = _merge_topic_pair(
    TOPICS,
    'AI Agents and Tool Calling',
    'Real-world Generative AI Applications',
    'Agents and Real-world Applications',
)


def seed_generative_ai_quizzes():
    course = Course.query.filter_by(name='Generative AI').first()
    if not course:
        raise RuntimeError('Generative AI course does not exist.')
    mentor = User.query.filter_by(role='mentor_admin').first()
    existing = course.quizzes.all()
    expected_titles = {f'Quiz {day}' for day in range(1, 16)}
    existing_questions = [question.question_text for quiz in existing for question in quiz.questions.all()]
    if (len(existing) != 15 or {quiz.title for quiz in existing} != expected_titles or
            any(quiz.questions.count() != 30 for quiz in existing) or
            len(existing_questions) != len(set(existing_questions))):
        for quiz in existing:
            db.session.delete(quiz)
        db.session.flush()

    for day_number, (topic, facts) in enumerate(TOPICS, start=1):
        quiz = Quiz.query.filter_by(course_id=course.id, title=f'Quiz {day_number}').first()
        if quiz and quiz.questions.count() == 30:
            continue
        if quiz:
            db.session.delete(quiz)
            db.session.flush()
        quiz = Quiz(
            title=f'Quiz {day_number}', description=topic,
            course_id=course.id, day_number=day_number,
            time_limit_minutes=0, total_marks=30,
            status='published', created_by=mentor.id if mentor else None,
        )
        db.session.add(quiz)
        db.session.flush()
        for question in _questions(facts):
            db.session.add(QuizQuestion(
                quiz_id=quiz.id,
                question_text=question['question_text'],
                option_a=question['options'][0],
                option_b=question['options'][1],
                option_c=question['options'][2],
                option_d=question['options'][3],
                correct_option=question['correct_option'],
                explanation=question['explanation'],
                marks=1, order_index=question['order_index'],
            ))
    db.session.commit()
